<h1><center><div style="direction:rtl;font-family:B Lotus, B Nazanin, Tahoma"> بسم الله الرحمن الرحیم</div></center></h1>

<h1><center><div style="direction:rtl;font-family:B Lotus, B Nazanin, Tahoma"> Classification with fully connected neural network with the IRIS dataset</div></center></h1>

## About
```
The structural data set of the findings includes 4 characteristics for the length and width of the sepals and petals, based on which the type of flower is distinguished from 3 different classes.
``` 

# Import required libraries

In [ ]:
import numpy as np
from tensorflow import ker# Datasetas

# About Dataset

+ Descriptions of this dataset are available on this website:

  + https://archive.ics.uci.edu/ml/datasets/iris 

---

+ Attribute Information:

    + sepal length in cm
    + sepal width in cm
    + petal length in cm
    + petal width in cm

---

+ class:

    + Iris Setosa
    + Iris Versicolour
    + Iris Virginica



# + Load Dataset

In [3]:
from sklearn.datasets import load_iris

iris_data = load_iris() # load the iris dataset

x = iris_data.data # Features
y = iris_data.target # Classes

print("Sample of Features:")
print(x[:5])

print("\n")

print("Sample of Classes:")
print(y[:5])

Sample of Features:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


Sample of Classes:
[0 0 0 0 0]


# + Preprocessing

In [4]:
# Convert data to a single column
y = y.reshape(-1, 1) 

print("Sample of Classes in a single column:")
y[:5]

Sample of Classes in a single column:


array([[0],
       [0],
       [0],
       [0],
       [0]])

In [9]:
# Store Number of classes befor convert to one-hot
print('Classes are:')
print(np.unique(y)) # Classes
number_of_classes = len(np.unique(y)) # 3

Classes are:
[0 1 2]


In [10]:
# Convert classes in one-hot

y = keras.utils.to_categorical(y , num_classes=3)
y[:5]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

# + Split the data

In [15]:
from sklearn.model_selection import train_test_split

# Split the data for training and testing
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.20)
train_x[:5]

array([[6.7, 3.1, 4.7, 1.5],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.7, 5.1, 1.9],
       [4.9, 3.1, 1.5, 0.1],
       [6.9, 3.1, 4.9, 1.5]])

# + Initial Neural Network

In [20]:
from keras.models import Sequential
from keras.layers import Dense, Dropout

# Store input dimention
size_sample , dimantion = x.shape

model = Sequential()
model.add(Dense(10 , activation='relu' , input_dim=dimantion)) # 1st Layerst
model.add(Dense(10 , activation='relu' )) # 2nd Layer
model.add(Dropout(0.5)) # Droupout ( kill 50% of neurals)
model.add(Dense(number_of_classes, activation='softmax')) # Final Layer

In [22]:
# Summary of created Neural Network
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_9 (Dense)             (None, 10)                50        
                                                                 
 dense_10 (Dense)            (None, 10)                110       
                                                                 
 dropout_3 (Dropout)         (None, 10)                0         
                                                                 
 dense_11 (Dense)            (None, 3)                 33        
                                                                 
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________


# + Optimizing


In [24]:
from tensorflow.keras.optimizers import Adam

# Adam optimizer with learning rate of 0.001
optimizer = Adam(lr=0.001)
model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])


# + Learning

In [25]:
model.fit(train_x,train_y,epochs=200,batch_size=5)

Epoch 1/200
24/24 [==============================] - 1s 5ms/step - loss: 1.2123 - accuracy: 0.2500
Epoch 2/200
24/24 [==============================] - 0s 4ms/step - loss: 1.1803 - accuracy: 0.3167
Epoch 3/200
24/24 [==============================] - 0s 5ms/step - loss: 1.1242 - accuracy: 0.3000
Epoch 4/200
24/24 [==============================] - 0s 5ms/step - loss: 1.0591 - accuracy: 0.3417
Epoch 5/200
24/24 [==============================] - 0s 6ms/step - loss: 1.0501 - accuracy: 0.3250
Epoch 6/200
24/24 [==============================] - 0s 5ms/step - loss: 1.0213 - accuracy: 0.3167
Epoch 7/200
24/24 [==============================] - 0s 4ms/step - loss: 0.9595 - accuracy: 0.4833
Epoch 8/200
24/24 [==============================] - 0s 4ms/step - loss: 0.9967 - accuracy: 0.4917
Epoch 9/200
24/24 [==============================] - 0s 5ms/step - loss: 0.9336 - accuracy: 0.5583
Epoch 10/200
24/24 [==============================] - 0s 4ms/step - loss: 0.9414 - accuracy: 0.5750
Epoch 11/