<h1><center><div style="direction:rtl;font-family:B Lotus, B Nazanin, Tahoma"> بسم الله الرحمن الرحیم</div></center></h1>

<h1><center><div style="direction:rtl;font-family:B Lotus, B Nazanin, Tahoma"> Classification with fully connected neural network with the IRIS dataset</div></center></h1>

## About
```
The structural data set of the findings includes 4 characteristics for the length and width of the sepals and petals, based on which the type of flower is distinguished from 3 different classes.
``` 

# Import required libraries

In [1]:
import numpy as np
from tensorflow import keras # Datasetas

2022-03-16 17:57:44.023190: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-03-16 17:57:44.023234: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


# About Dataset

+ Descriptions of this dataset are available on this website:

  + https://archive.ics.uci.edu/ml/datasets/iris 

---

+ Attribute Information:

    + sepal length in cm
    + sepal width in cm
    + petal length in cm
    + petal width in cm

---

+ class:

    + Iris Setosa
    + Iris Versicolour
    + Iris Virginica



# + Load Dataset

In [2]:
from sklearn.datasets import load_iris

iris_data = load_iris() # load the iris dataset

x = iris_data.data # Features
y = iris_data.target # Classes

print("Sample of Features:")
print(x[:5])

print("\n")

print("Sample of Classes:")
print(y[:5])

Sample of Features:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


Sample of Classes:
[0 0 0 0 0]


# + Preprocessing

In [3]:
# Convert data to a single column
y = y.reshape(-1, 1) 

print("Sample of Classes in a single column:")
y[:5]

Sample of Classes in a single column:


array([[0],
       [0],
       [0],
       [0],
       [0]])

In [4]:
# Store Number of classes befor convert to one-hot
print('Classes are:')
print(np.unique(y)) # Classes
number_of_classes = len(np.unique(y)) # 3
number_of_classes

Classes are:
[0 1 2]


3

In [5]:
# Convert classes in one-hot

y = keras.utils.to_categorical(y , num_classes=3)
y[:5]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

# + Split the data

In [6]:
from sklearn.model_selection import train_test_split

# Split the data for training and testing
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.20)
train_x[:5]

array([[5.9, 3. , 4.2, 1.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.3, 2.9, 5.6, 1.8],
       [5.4, 3.9, 1.3, 0.4],
       [4.8, 3.1, 1.6, 0.2]])

# + Initial Neural Network

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Dropout

# Store input dimention
size_sample , dimantion = x.shape

model = Sequential()
model.add(Dense(10 , activation='relu' , input_dim=dimantion)) # 1st Layerst
model.add(Dense(10 , activation='relu' )) # 2nd Layer
model.add(Dropout(0.5)) # Droupout ( kill 50% of neurals)
model.add(Dense(number_of_classes, activation='softmax')) # Final Layer

In [8]:
# Summary of created Neural Network
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 10)                50        
                                                                 
 dense_1 (Dense)             (None, 10)                110       
                                                                 
 dropout (Dropout)           (None, 10)                0         
                                                                 
 dense_2 (Dense)             (None, 3)                 33        
                                                                 
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________


# + Optimizing


In [9]:
from tensorflow.keras.optimizers import Adam

# Adam optimizer with learning rate of 0.001
optimizer = Adam(lr=0.001)
model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])


/usr/local/lib/python3.9/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


# + Learning

In [10]:
model.fit(train_x,train_y,epochs=200,batch_size=5,validation_split=0.2)

Epoch 1/200
20/20 [==============================] - 2s 33ms/step - loss: 1.1639 - accuracy: 0.3542 - val_loss: 1.1512 - val_accuracy: 0.3333
Epoch 2/200
20/20 [==============================] - 0s 10ms/step - loss: 1.1314 - accuracy: 0.3646 - val_loss: 1.1195 - val_accuracy: 0.3333
Epoch 3/200
20/20 [==============================] - 0s 10ms/step - loss: 1.1642 - accuracy: 0.2604 - val_loss: 1.0857 - val_accuracy: 0.3333
Epoch 4/200
20/20 [==============================] - 0s 11ms/step - loss: 1.0866 - accuracy: 0.3750 - val_loss: 1.0033 - val_accuracy: 0.3333
Epoch 5/200
20/20 [==============================] - 0s 11ms/step - loss: 1.0025 - accuracy: 0.4271 - val_loss: 0.9703 - val_accuracy: 0.3333
Epoch 6/200
20/20 [==============================] - 0s 9ms/step - loss: 1.0052 - accuracy: 0.3958 - val_loss: 0.9444 - val_accuracy: 0.3750
Epoch 7/200
20/20 [==============================] - 0s 11ms/step - loss: 0.9823 - accuracy: 0.4271 - val_loss: 0.9172 - val_accuracy: 0.6250
Epoch 8

# + Evaluatution

In [14]:
# Test on unseen data
results = model.evaluate(test_x, test_y)

print('Final test set loss: {:4f}'.format(results[0]))
print('Final test set accuracy: {:4f}'.format(results[1]))

1/1 [==============================] - 0s 267ms/step - loss: 0.0509 - accuracy: 1.0000
Final test set loss: 0.050933
Final test set accuracy: 1.000000
