<h1><center><div style="direction:rtl;font-family:B Lotus, B Nazanin, Tahoma"> بسم الله الرحمن الرحیم</div></center></h1>

<h1><center><div style="direction:rtl;font-family:B Lotus, B Nazanin, Tahoma"> Classification with fully connected neural network with the IRIS dataset</div></center></h1>

## About
```
The structural data set of the findings includes 4 characteristics for the length and width of the sepals and petals, based on which the type of flower is distinguished from 3 different classes.
``` 

# Import required libraries

In [ ]:
import numpy as np
from tensorflow import ker# Datasetas

# About Dataset

+ Descriptions of this dataset are available on this website:

  + https://archive.ics.uci.edu/ml/datasets/iris 

---

+ Attribute Information:

    + sepal length in cm
    + sepal width in cm
    + petal length in cm
    + petal width in cm

---

+ class:

    + Iris Setosa
    + Iris Versicolour
    + Iris Virginica



# + Load Dataset

In [3]:
from sklearn.datasets import load_iris

iris_data = load_iris() # load the iris dataset

x = iris_data.data # Features
y = iris_data.target # Classes

print("Sample of Features:")
print(x[:5])

print("\n")

print("Sample of Classes:")
print(y[:5])

Sample of Features:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


Sample of Classes:
[0 0 0 0 0]


# + Preprocessing

In [4]:
# Convert data to a single column
y = y.reshape(-1, 1) 

print("Sample of Classes in a single column:")
y[:5]

Sample of Classes in a single column:


array([[0],
       [0],
       [0],
       [0],
       [0]])

In [9]:
# Store Number of classes befor convert to one-hot
print('Classes are:')
print(np.unique(y)) # Classes
number_of_classes = len(np.unique(y)) # 3

Classes are:
[0 1 2]


In [10]:
# Convert classes in one-hot

y = keras.utils.to_categorical(y , num_classes=3)
y[:5]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

# + Split the data

In [15]:
from sklearn.model_selection import train_test_split

# Split the data for training and testing
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.20)
train_x[:5]

array([[6.7, 3.1, 4.7, 1.5],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.7, 5.1, 1.9],
       [4.9, 3.1, 1.5, 0.1],
       [6.9, 3.1, 4.9, 1.5]])

# + Make the Neural Network

In [19]:
from keras.models import Sequential
from keras.layers import Dense, Dropout

# Store input dimention
size_sample , dimantion = x.shape

model = Sequential()
model.add(Dense(10 , activation='relu' , input_dim=dimantion)) # 1st Layerst
model.add(Dense(10 , activation='relu' )) # 2nd Layer
model.add(Dropout(0.5)) # Droupout ( kill 50% of neurals)
model.add(Dense(number_of_classes, activation='softmax')) # Final Layer